version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
      - ./.docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    links:
      - php
  php:
    container_name: php-fpm
    build: ./.docker/php
    links:
      - db
    volumes:
      - ./:/var/www
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=400M
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=dev
      - PMA_PASSWORD=dev
    links:
      - db
  db:
    container_name: mysql
    image: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    restart: always
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
  blackfire:
    container_name: blackfire
    image: blackfire/blackfire:2
    ports: [ "8307" ]
    environment:
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN

volumes:
  mysql: